// Banco de preguntas — Oposiciones Galicia, Educación Infantil
// 25 bloques (temario), 6 preguntas tipo test por bloque, con explicación.
const QUESTION_BANK = [
{
  id: "b01", title: "Alimentación, Nutrición y Dietética",
  questions: [
    {q:"¿Cuál de los siguientes NO es uno de los principios inmediatos básicos de la alimentación?",
     o:["Hidratos de carbono","Proteínas","Vitaminas liposolubles","Fibra dietética"],
     c:3, e:"Los tres principios inmediatos son hidratos de carbono, proteínas y grasas (lípidos). La fibra y las vitaminas son nutrientes reguladores, no principios inmediatos."},
    {q:"Según las recomendaciones de introducción de la alimentación complementaria, el periodo de lactancia materna exclusiva recomendado por la OMS es de:",
     o:["3 meses","6 meses","9 meses","12 meses"],
     c:1, e:"La OMS recomienda lactancia materna exclusiva hasta los 6 meses, con introducción progresiva de alimentación complementaria a partir de esa edad."},
    {q:"En la etapa de Educación Infantil, ¿cuál es el objetivo prioritario del comedor escolar en relación con la educación para la salud?",
     o:["Cubrir únicamente las necesidades calóricas","Fomentar hábitos alimentarios saludables y autonomía en la comida","Sustituir la alimentación familiar","Priorizar la rapidez del servicio"],
     c:1, e:"El comedor escolar es un espacio educativo más: se trabajan hábitos de higiene, autonomía (comer solo, usar cubiertos) y una alimentación equilibrada y variada."},
    {q:"¿Qué trastorno de conducta alimentaria es más frecuente detectar en la etapa infantil, ligado a la neofobia alimentaria?",
     o:["Anorexia nerviosa","Rechazo o selectividad ante alimentos nuevos","Bulimia","Pica en adolescentes"],
     c:1, e:"La neofobia alimentaria (rechazo a probar alimentos nuevos o desconocidos) es habitual entre los 2 y 6 años y forma parte del desarrollo típico, aunque debe abordarse educativamente."},
    {q:"La 'rueda de los alimentos' o la 'pirámide alimentaria' se emplea en Educación Infantil fundamentalmente como:",
     o:["Recurso decorativo del aula","Recurso didáctico para clasificar alimentos y trabajar hábitos saludables","Instrumento de evaluación psicomotriz","Material exclusivo del área de matemáticas"],
     c:1, e:"Son recursos gráficos que ayudan a clasificar los grupos de alimentos y a iniciar a los niños y niñas en la comprensión de una dieta equilibrada."},
    {q:"¿Cuál de estas es una pauta correcta para el desayuno en el aula de Infantil (almuerzo de media mañana)?",
     o:["Priorizar bollería industrial por ser más atractiva","Ofrecer variedad con fruta, lácteos o pan, evitando ultraprocesados","Eliminar cualquier momento de alimentación en el centro","Exigir que todos coman exactamente la misma cantidad"],
     c:1, e:"Se recomienda variar entre fruta, lácteos, pan/cereales, limitando azúcares y productos ultraprocesados, respetando además el ritmo individual de cada niño o niña."}
  ]
},
{
  id: "b02", title: "Características Generales del Niño y la Niña hasta los Seis Años",
  questions: [
    {q:"El desarrollo infantil se caracteriza por seguir dos leyes fundamentales de maduración:",
     o:["Ley cefalocaudal y ley proximodistal","Ley de la oferta y la demanda","Ley del efecto y ley del ejercicio","Ley de Piaget y ley de Freud"],
     c:0, e:"El desarrollo motor progresa de la cabeza a los pies (cefalocaudal) y del centro del cuerpo hacia las extremidades (proximodistal)."},
    {q:"El desarrollo infantil se considera un proceso:",
     o:["Lineal e idéntico en todos los niños","Global e integrado, en el que interactúan todas las áreas","Exclusivamente determinado por la genética","Independiente entre las distintas dimensiones (motriz, cognitiva, afectiva...)"],
     c:1, e:"El desarrollo es un proceso globalizado: los avances en un área (p. ej. motriz) influyen y se relacionan con los de otras (cognitiva, afectiva, social)."},
    {q:"¿Qué característica NO es propia del desarrollo evolutivo de 0 a 6 años?",
     o:["Gran plasticidad neuronal","Ritmo de desarrollo idéntico entre individuos","Dependencia inicial del adulto que evoluciona hacia la autonomía","Egocentrismo característico del pensamiento preoperacional"],
     c:1, e:"Aunque existen hitos evolutivos generales, el ritmo de desarrollo es individual: cada niño o niña tiene su propio ritmo madurativo dentro de una secuencia común."},
    {q:"El concepto de 'periodos sensibles' del desarrollo, tan relevante en esta etapa, fue especialmente desarrollado por:",
     o:["B.F. Skinner","Maria Montessori","Sigmund Freud","Ivan Pávlov"],
     c:1, e:"Montessori (recogiendo ideas de De Vries) habla de periodos sensibles: fases de especial receptividad para adquirir determinadas capacidades (lenguaje, orden, movimiento...)."},
    {q:"Desde el punto de vista legal, ¿en cuántos ciclos se organiza la etapa de Educación Infantil en España?",
     o:["Un ciclo único de 0 a 6 años","Dos ciclos: 0-3 y 3-6 años","Tres ciclos de dos años cada uno","Cuatro cursos sin ciclos diferenciados"],
     c:1, e:"La Educación Infantil se organiza en dos ciclos: el primero de 0 a 3 años y el segundo de 3 a 6 años, cada uno con su propia identidad pedagógica."},
    {q:"¿Cuál de los siguientes es un factor que influye en el desarrollo infantil según el enfoque bioecológico de Bronfenbrenner?",
     o:["Únicamente la genética individual","Los distintos contextos o sistemas (micro, meso, exo y macrosistema) en interacción con la persona","Solo el rendimiento escolar","Exclusivamente el nivel socioeconómico familiar"],
     c:1, e:"Bronfenbrenner explica el desarrollo como resultado de la interacción de la persona con sistemas anidados: microsistema, mesosistema, exosistema y macrosistema."}
  ]
},
{
  id: "b03", title: "Consecución de las Capacidades Generales de la Etapa mediante los Objetivos y Contenidos de las Áreas del Currículo",
  questions: [
    {q:"Según el currículo LOMLOE (Decreto 150/2022 en Galicia), las áreas de Educación Infantil son:",
     o:["Identidad y autonomía personal, Medio físico y social, Comunicación y representación","Crecimiento en armonía, Descubrimiento y exploración del entorno, Comunicación y representación de la realidad","Lengua, Matemáticas y Conocimiento del medio","Psicomotricidad, Lenguaje y Convivencia"],
     c:1, e:"El currículo LOMLOE sustituye las tres áreas clásicas por: Crecimiento en armonía, Descubrimiento y exploración del entorno, y Comunicación y representación de la realidad."},
    {q:"Los objetivos generales de la etapa de Educación Infantil se formulan en términos de:",
     o:["Contenidos a memorizar","Capacidades a desarrollar","Estándares de aprendizaje evaluables","Competencias exclusivamente motrices"],
     c:1, e:"A diferencia de otras etapas, los objetivos de Infantil se expresan como capacidades generales que el alumnado debe desarrollar, no como aprendizajes concretos y cerrados."},
    {q:"Las áreas del currículo de Infantil se caracterizan por un enfoque:",
     o:["Disciplinar y compartimentado","Globalizador e interdependiente","Exclusivamente instrumental","Centrado solo en contenidos conceptuales"],
     c:1, e:"Las áreas no se trabajan de forma aislada; se conciben como ámbitos de experiencia interrelacionados dentro de una perspectiva globalizadora del aprendizaje."},
    {q:"Los contenidos en Educación Infantil se organizan tradicionalmente en tres tipos, según su naturaleza:",
     o:["Conceptuales, procedimentales y actitudinales","Verbales, no verbales y mixtos","Obligatorios, optativos y libres","Motrices, cognitivos y sociales"],
     c:0, e:"Aunque en la etapa priman los procedimentales y actitudinales, la clasificación clásica distingue contenidos conceptuales (saber), procedimentales (saber hacer) y actitudinales (saber ser)."},
    {q:"¿Qué papel cumplen los objetivos de área respecto a los objetivos generales de etapa?",
     o:["Son independientes entre sí","Concretan y desarrollan las capacidades generales de la etapa en cada ámbito de experiencia","Sustituyen a los objetivos generales","Solo se aplican en el segundo ciclo"],
     c:1, e:"Los objetivos de cada área concretan, desde su ámbito específico, las capacidades generales establecidas para toda la etapa."},
    {q:"El principio de que los aprendizajes deben adquirirse a través de la actividad infantil y la experimentación se relaciona directamente con el principio metodológico de:",
     o:["Aprendizaje memorístico","Aprendizaje significativo y globalizado","Instrucción directa exclusivamente","Evaluación sumativa"],
     c:1, e:"El currículo de Infantil se sustenta en el aprendizaje significativo (Ausubel) y globalizado, partiendo de la actividad y la experimentación directa del niño o niña."}
  ]
},
{
  id: "b04", title: "Desarrollo Cognitivo hasta los Seis Años",
  questions: [
    {q:"Según Piaget, el niño de 0 a 6 años atraviesa, sucesivamente, los estadios:",
     o:["Sensoriomotor y preoperacional","Operaciones concretas y formales","Solo el estadio preoperacional","Sensoriomotor y operaciones formales"],
     c:0, e:"De 0 a 2 años se da el estadio sensoriomotor, y de 2 a 6-7 años el estadio preoperacional, previo a las operaciones concretas (7-11 años)."},
    {q:"El 'egocentrismo intelectual' propio del pensamiento preoperacional se refiere a:",
     o:["El niño no puede jugar con otros","La dificultad para adoptar el punto de vista de otra persona","Un trastorno de conducta","La incapacidad de hablar"],
     c:1, e:"El egocentrismo cognitivo (no confundir con egoísmo) es la dificultad del niño preoperacional para descentrarse y considerar perspectivas distintas a la propia."},
    {q:"La noción de 'permanencia del objeto' se adquiere durante el estadio:",
     o:["Preoperacional","Sensoriomotor","Operaciones concretas","Operaciones formales"],
     c:1, e:"La permanencia del objeto (saber que algo sigue existiendo aunque no se vea) se consolida durante el periodo sensoriomotor, en torno a los 8-12 meses."},
    {q:"La 'zona de desarrollo próximo' (ZDP) es un concepto clave de:",
     o:["Jean Piaget","Lev Vygotski","B.F. Skinner","Sigmund Freud"],
     c:1, e:"Vygotski definió la ZDP como la distancia entre lo que el niño puede hacer solo y lo que puede lograr con ayuda de un adulto o iguales más capaces."},
    {q:"El fenómeno de 'no conservación' (por ejemplo, creer que hay más líquido en un vaso alto y estrecho que en uno bajo y ancho) es típico de:",
     o:["El estadio sensoriomotor","El pensamiento preoperacional","Las operaciones concretas","Las operaciones formales"],
     c:1, e:"La falta de conservación de cantidad, masa o número es característica del pensamiento preoperacional, ligada al centramiento y a la irreversibilidad del pensamiento."},
    {q:"El concepto de 'andamiaje' (scaffolding), estrechamente ligado a la ZDP de Vygotski, fue desarrollado por:",
     o:["Jerome Bruner","Jean Piaget","Ovide Decroly","Henri Wallon"],
     c:0, e:"Bruner acuñó el término 'andamiaje' para describir el apoyo ajustado que un adulto ofrece al niño, retirándolo progresivamente a medida que gana autonomía."}
  ]
},
{
  id: "b05", title: "Educación Para la Salud",
  questions: [
    {q:"La Educación para la Salud en Infantil se aborda fundamentalmente como:",
     o:["Un área independiente con horario propio","Un contenido transversal presente en toda la práctica educativa","Una actividad exclusiva del área de psicomotricidad","Responsabilidad exclusiva de las familias"],
     c:1, e:"La Educación para la Salud es un tema transversal que impregna hábitos de higiene, alimentación, descanso y autonomía a lo largo de toda la jornada escolar."},
    {q:"¿Cuál de los siguientes es un hábito de autonomía personal relacionado con la salud que se trabaja en Infantil?",
     o:["El lavado de manos y el control de esfínteres","La resolución de operaciones matemáticas","La lectoescritura formal","El aprendizaje de un segundo idioma"],
     c:0, e:"El control de esfínteres, el lavado de manos, el cepillado de dientes o vestirse solo son hábitos de autonomía y salud propios de esta etapa."},
    {q:"Según la OMS, la salud se define como:",
     o:["La ausencia de enfermedad únicamente","Un estado de completo bienestar físico, mental y social","Un estado exclusivamente físico","La capacidad de trabajar sin descanso"],
     c:1, e:"La OMS define la salud de forma integral, no solo como ausencia de enfermedad, sino como bienestar físico, psíquico y social."},
    {q:"El calendario de vacunación infantil en el marco escolar es responsabilidad principal de:",
     o:["El profesorado de Educación Infantil","Las familias y el sistema sanitario, con función de apoyo del centro","El equipo directivo del centro exclusivamente","La inspección educativa"],
     c:1, e:"El seguimiento del calendario vacunal corresponde a familias y sanidad; el centro educativo colabora fomentando hábitos de salud, pero no gestiona las vacunas."},
    {q:"¿Qué papel juega la siesta o el momento de descanso en las aulas de primer ciclo de Infantil?",
     o:["Es prescindible y no influye en el desarrollo","Responde a necesidades fisiológicas y favorece el desarrollo neurológico","Solo tiene función de control disciplinario","Debe eliminarse a partir del primer año"],
     c:1, e:"El descanso responde a necesidades fisiológicas reales del bebé y niño pequeño, y es fundamental para su desarrollo físico y neurológico."},
    {q:"La prevención de accidentes infantiles en el aula se relaciona con el principio de:",
     o:["Seguridad y bienestar como condición para el aprendizaje","Aprendizaje memorístico","Evaluación sumativa","Autonomía sin supervisión adulta"],
     c:0, e:"Un entorno seguro es condición previa para que se produzcan aprendizajes: la prevención de riesgos y accidentes forma parte de la educación para la salud."}
  ]
},
{
  id: "b06", title: "El Desarrollo de la Personalidad",
  questions: [
    {q:"El apego, según la teoría de John Bowlby, se define como:",
     o:["Un vínculo afectivo duradero entre el niño y su figura de referencia","Un trastorno de conducta infantil","Una etapa del desarrollo cognitivo","Un tipo de juego simbólico"],
     c:0, e:"Bowlby define el apego como el vínculo afectivo que el bebé establece con su cuidador principal, con función de protección y base para el desarrollo emocional."},
    {q:"Mary Ainsworth, a través de la 'situación extraña', identificó distintos tipos de apego, entre ellos:",
     o:["Apego seguro, ansioso-evitativo y ansioso-ambivalente/resistente","Apego primario, secundario y terciario","Apego cognitivo, motor y afectivo","Apego únicamente seguro o inseguro sin subtipos"],
     c:0, e:"El experimento de la 'situación extraña' de Ainsworth clasificó el apego en seguro, inseguro-evitativo e inseguro-ambivalente (más tarde se añadió el desorganizado)."},
    {q:"Según Erik Erikson, el conflicto psicosocial característico del primer año de vida es:",
     o:["Autonomía frente a vergüenza y duda","Confianza básica frente a desconfianza","Iniciativa frente a culpa","Identidad frente a confusión de rol"],
     c:1, e:"Erikson sitúa en el primer año de vida el conflicto 'confianza básica frente a desconfianza', resuelto favorablemente gracias a unos cuidados consistentes."},
    {q:"El autoconcepto y la autoestima en la etapa infantil se construyen fundamentalmente a través de:",
     o:["La herencia genética exclusivamente","Las interacciones con adultos e iguales y el feedback que reciben","La maduración neurológica sin influencia ambiental","Los contenidos curriculares matemáticos"],
     c:1, e:"El autoconcepto se construye socialmente, a través de las valoraciones e interacciones con adultos significativos e iguales."},
    {q:"El temperamento infantil, entendido como base biológica de la personalidad, fue estudiado especialmente por:",
     o:["Thomas y Chess","Piaget","Vygotski","Skinner"],
     c:0, e:"Alexander Thomas y Stella Chess, en el Estudio Longitudinal de Nueva York, describieron los tipos de temperamento infantil: fácil, difícil y de respuesta lenta."},
    {q:"La crisis de oposición o 'etapa del no', muy característica en torno a los dos-tres años, se relaciona con:",
     o:["La afirmación del yo y la búsqueda de autonomía","Un trastorno de conducta que debe corregirse con castigo","La ausencia de vínculo afectivo","El fracaso escolar"],
     c:0, e:"En torno a los 2-3 años el niño busca afirmar su identidad y autonomía frente al adulto; es una fase normativa del desarrollo de la personalidad."}
  ]
},
{
  id: "b07", title: "El Desarrollo del Lenguaje",
  questions: [
    {q:"La etapa prelingüística del desarrollo del lenguaje abarca aproximadamente:",
     o:["De 0 a 12 meses","De 2 a 4 años","De 4 a 6 años","Toda la etapa de Infantil"],
     c:0, e:"La etapa prelingüística (balbuceo, laleo, gestos comunicativos) se extiende desde el nacimiento hasta la aparición de las primeras palabras, en torno al año."},
    {q:"El 'habla telegráfica', propia de los 18-24 meses, se caracteriza por:",
     o:["Frases de una sola palabra que sirven de holofrase","Combinar dos o tres palabras clave omitiendo nexos y artículos","Un dominio completo de la sintaxis adulta","La ausencia total de comunicación verbal"],
     c:1, e:"El habla telegráfica combina palabras clave ('mamá agua') omitiendo elementos gramaticales, de forma similar a un telegrama."},
    {q:"Noam Chomsky defendió que la adquisición del lenguaje se explica por:",
     o:["El refuerzo y la imitación exclusivamente","Un dispositivo innato de adquisición del lenguaje (LAD)","La maduración motriz","El aprendizaje por ensayo y error"],
     c:1, e:"Chomsky propuso que los humanos poseen una capacidad innata (LAD, Language Acquisition Device) que facilita la adquisición de las estructuras gramaticales."},
    {q:"Skinner, desde el conductismo, explicó la adquisición del lenguaje a través de:",
     o:["El refuerzo, la imitación y el condicionamiento operante","Un dispositivo innato exclusivo","La zona de desarrollo próximo","Los esquemas sensoriomotores"],
     c:0, e:"Skinner defendía que el lenguaje se adquiere como cualquier otra conducta: mediante imitación, refuerzo y condicionamiento operante del entorno."},
    {q:"El 'habla privada' o 'lenguaje egocéntrico' que el niño usa mientras juega, según Vygotski, cumple la función de:",
     o:["No tiene ninguna función, es un error de desarrollo","Autorregular y guiar su propio pensamiento y acción","Comunicarse exclusivamente con los adultos","Sustituir al lenguaje social"],
     c:1, e:"Para Vygotski, el habla privada tiene una función autorreguladora: ayuda al niño a planificar y guiar su propia actividad, y con el tiempo se interioriza como pensamiento verbal."},
    {q:"¿Cuál de estos NO es un componente del lenguaje que se trabaje en la evaluación/desarrollo lingüístico infantil?",
     o:["Fonológico","Semántico","Pragmático","Psicomotor"],
     c:3, e:"Los componentes del lenguaje son fonológico, morfosintáctico, semántico y pragmático; lo psicomotor pertenece a otra dimensión del desarrollo."}
  ]
},
{
  id: "b08", title: "El Desarrollo Psicomotor en los Niños y Niñas hasta los Seis Años",
  questions: [
    {q:"La psicomotricidad se define como una disciplina que integra:",
     o:["Únicamente aspectos motrices","Las funciones motrices, cognitivas y afectivas de la persona","Solo aspectos anatómicos","Exclusivamente contenidos deportivos"],
     c:1, e:"La psicomotricidad concibe el movimiento como expresión global de la persona, integrando lo motor, lo cognitivo y lo afectivo-relacional."},
    {q:"El esquema corporal, es decir, la representación mental del propio cuerpo, se consolida fundamentalmente:",
     o:["Antes de nacer","A lo largo de la etapa infantil, en interacción con el movimiento y la experiencia","De forma instantánea al nacer","Solo en la adolescencia"],
     c:1, e:"El esquema corporal se construye progresivamente durante la infancia gracias a la experiencia motriz, sensorial y perceptiva del propio cuerpo."},
    {q:"La marcha autónoma (caminar sin apoyo) se adquiere, de forma orientativa, en torno a:",
     o:["Los 3-4 meses","Los 12-15 meses","Los 3 años","Los 5 años"],
     c:1, e:"La marcha autónoma suele consolidarse entre los 12 y 15 meses, aunque existe variabilidad individual normal."},
    {q:"La motricidad fina hace referencia a:",
     o:["Los grandes grupos musculares (andar, saltar, correr)","Movimientos precisos de manos y dedos (pinza, recorte, ensartado)","El control postural global","La lateralidad exclusivamente"],
     c:1, e:"La motricidad fina implica movimientos de precisión de manos y dedos, como la pinza digital, el recorte o el garabateo."},
    {q:"La lateralidad (predominio de un lado del cuerpo) se considera, en general, definida de forma estable en torno a:",
     o:["Los 6 meses","Los 2-3 años","Los 5-6 años","Nunca se define"],
     c:2, e:"Aunque hay un proceso previo de exploración bilateral, la lateralidad suele quedar establecida de forma más estable hacia el final de la etapa infantil (5-6 años)."},
    {q:"En la práctica psicomotriz de Bernard Aucouturier, la sala de psicomotricidad se organiza típicamente en fases o momentos que incluyen:",
     o:["Ritual de entrada, juego sensoriomotor/simbólico y momento de representación/relajación","Únicamente ejercicios de gimnasia dirigida","Solo actividades de mesa","Exclusivamente juego libre sin estructura"],
     c:0, e:"La práctica psicomotriz vivenciada (Aucouturier) estructura la sesión en un ritual de entrada, un momento de juego motor/simbólico y un cierre de representación y calma."}
  ]
},
{
  id: "b09", title: "El Niño Descubre a los Otros",
  questions: [
    {q:"Según Jean Piaget, el juego que caracteriza a niños de 2-3 años, en el que juegan uno junto a otro sin interactuar realmente, se denomina:",
     o:["Juego cooperativo","Juego paralelo","Juego asociativo","Juego reglado"],
     c:1, e:"Mildred Parten (adoptada en la literatura sobre socialización infantil) describió el juego paralelo como aquel en que los niños juegan cerca unos de otros pero sin interacción directa."},
    {q:"El proceso de socialización en la etapa infantil se produce inicialmente a través de:",
     o:["La escuela exclusivamente","La familia, como primer agente socializador","Los medios de comunicación","El grupo de iguales exclusivamente desde el nacimiento"],
     c:1, e:"La familia constituye el primer y más influyente agente de socialización, proporcionando las primeras pautas de relación e interacción social."},
    {q:"La 'teoría de la mente', es decir, la capacidad de atribuir estados mentales a otras personas, se desarrolla de forma más clara en torno a:",
     o:["Los 6 meses","Los 4-5 años","Los 10 años","Nunca en la etapa infantil"],
     c:1, e:"En torno a los 4-5 años los niños superan tareas clásicas de falsa creencia, mostrando una comprensión más clara de que otros pueden tener creencias distintas a las propias."},
    {q:"Los conflictos entre iguales en el aula de Infantil deben entenderse, desde el punto de vista educativo, como:",
     o:["Situaciones a evitar siempre mediante la intervención inmediata del adulto","Oportunidades de aprendizaje social que requieren un acompañamiento educativo ajustado","Muestras de mala conducta que deben sancionarse","Fenómenos irrelevantes para el desarrollo social"],
     c:1, e:"Los conflictos son inherentes a la vida en grupo y constituyen oportunidades para aprender habilidades de negociación, empatía y regulación emocional, con el acompañamiento del adulto."},
    {q:"La empatía, como capacidad de comprender y compartir los sentimientos de otros, comienza a manifestarse de forma incipiente:",
     o:["Ya en el primer año de vida (contagio emocional, preocupación empática)","Únicamente a partir de los 7 años","Nunca antes de la adolescencia","Solo tras la escolarización obligatoria"],
     c:0, e:"Desde el primer año se observan precursores de la empatía, como el contagio emocional ante el llanto de otro bebé, que evoluciona hacia formas más complejas."},
    {q:"El 'juego cooperativo', en el que existe una meta común y reparto de roles, es propio de:",
     o:["El primer año de vida","El segundo ciclo de Infantil (4-6 años), como culminación del desarrollo social del juego","Nunca aparece en Infantil","Solo se da en la etapa adulta"],
     c:1, e:"El juego cooperativo, con organización de roles y objetivo compartido, representa el nivel más avanzado de juego social y se consolida hacia el final de la etapa infantil."}
  ]
},
{
  id: "b10", title: "Equipamiento, Material Didáctico y Materiales Curriculares en Educación Infantil",
  questions: [
    {q:"Los materiales didácticos en Infantil deben cumplir, entre otros, el criterio de:",
     o:["Ser exclusivamente comerciales y estructurados","Adecuación a las características evolutivas y seguridad para el niño o niña","Priorizar el coste elevado sobre la funcionalidad","Ser únicamente de un solo uso posible"],
     c:1, e:"Los materiales deben ser seguros, adecuados a la edad y polivalentes, favoreciendo la manipulación, exploración y el juego."},
    {q:"El material Montessori se caracteriza principalmente por:",
     o:["Ser autocorrectivo y estar diseñado para el trabajo autónomo del niño","Requerir siempre la supervisión constante del adulto para su uso","Ser exclusivamente simbólico, sin manipulación","No tener ninguna finalidad didáctica"],
     c:0, e:"Los materiales Montessori están diseñados para que el propio niño detecte el error (autocorrección) y trabaje con autonomía, respetando su ritmo."},
    {q:"Los 'dones' o 'regalos' (Gaben), material estructurado de bloques y formas geométricas, fueron creados por:",
     o:["Friedrich Fröbel","Ovide Decroly","Loris Malaguzzi","Célestin Freinet"],
     c:0, e:"Fröbel, creador del concepto de 'kindergarten', diseñó los dones o Gaben, un conjunto de materiales para el juego educativo sensorial y manipulativo."},
    {q:"Se denomina material fungible a aquel que:",
     o:["Se puede reutilizar indefinidamente","Se consume o se gasta con el uso (papel, pintura, pegamento...)","Solo se usa en el área de psicomotricidad","Está prohibido en Educación Infantil"],
     c:1, e:"El material fungible es el que se consume con el uso, como papel, ceras, pegamento o pintura, en contraposición al material inventariable o no fungible."},
    {q:"La distribución y organización del material en el aula por 'rincones' o 'zonas' responde principalmente al principio de:",
     o:["Favorecer la autonomía, la elección y la actividad significativa del alumnado","Facilitar el control disciplinario del grupo","Reducir el número de materiales disponibles","Centralizar todo el material en manos del docente"],
     c:0, e:"La organización por rincones facilita que el niño elija, explore y actúe con autonomía, favoreciendo aprendizajes significativos y activos."},
    {q:"¿Qué normativa de referencia regula los requisitos de seguridad de los juguetes y materiales infantiles en la UE?",
     o:["El marcado CE y la Directiva europea de seguridad de los juguetes","No existe normativa específica","Solo normativa autonómica gallega","Normativa exclusivamente sanitaria hospitalaria"],
     c:0, e:"El marcado CE, en aplicación de la Directiva 2009/48/CE sobre seguridad de los juguetes, garantiza que un producto cumple los requisitos mínimos de seguridad en la UE."}
  ]
},
{
  id: "b11", title: "Evolución de la Expresión Plástica en los Niños y Niñas",
  questions: [
    {q:"La primera etapa de la evolución del dibujo infantil, caracterizada por trazos sin intención representativa, se denomina:",
     o:["Etapa del realismo visual","Etapa del garabateo","Etapa esquemática","Etapa del pseudonaturalismo"],
     c:1, e:"El garabateo (aproximadamente de 1-2 a 3-4 años) es la primera fase, con trazos motrices sin intención representativa inicial que luego adquieren nombre."},
    {q:"Según la clasificación clásica de Viktor Lowenfeld, tras el garabateo, la siguiente etapa evolutiva del dibujo infantil es:",
     o:["Etapa preesquemática","Etapa del realismo","Pseudonaturalismo","Periodo de la decisión"],
     c:0, e:"Lowenfeld sitúa tras el garabateo (2-4 años) la etapa preesquemática (4-7 años), en la que aparecen las primeras formas representativas intencionadas, como el 'renacuajo'."},
    {q:"El llamado 'monigote' o figura 'cabezón/renacuajo' en el dibujo de la figura humana es característico de:",
     o:["El final de la etapa de Infantil, hacia los 6 años","Los primeros intentos de representación de la figura humana, en torno a los 3-4 años","Bebés de pocos meses","Nunca aparece en el dibujo infantil"],
     c:1, e:"El 'renacuajo' (cabeza con extremidades directamente unidas) es una de las primeras formas de representación de la figura humana, típica en torno a los 3-4 años."},
    {q:"La expresión plástica en Infantil debe entenderse, desde el punto de vista educativo, como:",
     o:["Un medio de expresión y comunicación, no solo un producto estético final","Exclusivamente una actividad de tiempo libre sin valor educativo","Una habilidad técnica a evaluar por su perfección","Una actividad reservada al segundo ciclo"],
     c:0, e:"Más allá del resultado, la expresión plástica es un canal de expresión de emociones, ideas y representación del mundo del niño."},
    {q:"El papel del maestro o maestra ante las producciones plásticas infantiles debe ser preferentemente:",
     o:["Corregir el dibujo para que se ajuste a la realidad","Ofrecer modelos que el niño deba copiar de forma exacta","Respetar el proceso, ofrecer variedad de materiales y evitar valoraciones estéticas comparativas","Evaluar únicamente el resultado final con notas numéricas"],
     c:2, e:"El adulto debe respetar el proceso creativo, ofrecer recursos variados y evitar comparar o imponer modelos, valorando la expresión personal de cada niño."},
    {q:"El modelado con materiales como plastilina o arcilla favorece especialmente:",
     o:["La motricidad fina, la percepción táctil y la expresión tridimensional","Únicamente la memoria auditiva","El desarrollo del lenguaje oral exclusivamente","La lectoescritura formal"],
     c:0, e:"El modelado desarrolla la motricidad fina, la exploración sensorial táctil y permite representar en tres dimensiones, complementando al dibujo bidimensional."}
  ]
},
{
  id: "b12", title: "Formación de Capacidades Relacionadas con el Desarrollo Lógico-Matemático",
  questions: [
    {q:"Según Piaget, la construcción del número en el niño se apoya en dos tipos de relaciones lógicas básicas:",
     o:["Clasificación y seriación","Adición y sustracción","Medida y estimación","Geometría y topología"],
     c:0, e:"Piaget explica que el concepto de número se construye a partir de la síntesis de las operaciones de clasificación (agrupar por semejanzas) y seriación (ordenar según un criterio)."},
    {q:"El proceso de conteo en Infantil requiere el dominio de varios principios, entre ellos el 'principio de correspondencia biunívoca', que consiste en:",
     o:["Contar siempre empezando por el número más grande","Asignar una y solo una palabra-número a cada elemento contado","Memorizar la serie numérica sin contar objetos","Usar exclusivamente los dedos para contar"],
     c:1, e:"La correspondencia biunívoca (o uno a uno) implica asociar cada elemento de una colección con una única palabra-número, sin saltos ni repeticiones."},
    {q:"El aprendizaje de las nociones espaciales (dentro-fuera, arriba-abajo, cerca-lejos) en Infantil se apoya fundamentalmente en:",
     o:["La memorización verbal de conceptos abstractos","La propia experiencia corporal y motriz del niño en el espacio","Fichas y ejercicios de lápiz y papel exclusivamente","El uso exclusivo de las nuevas tecnologías"],
     c:1, e:"Las nociones espacio-temporales se construyen a partir de la vivencia corporal directa (moverse, situarse, desplazarse) antes de su representación gráfica o simbólica."},
    {q:"La clasificación, como capacidad lógico-matemática, consiste en:",
     o:["Ordenar elementos según un criterio de magnitud creciente o decreciente","Agrupar objetos según un criterio común (color, forma, tamaño...)","Contar objetos de una colección","Medir longitudes con instrumentos"],
     c:1, e:"Clasificar implica agrupar elementos que comparten una característica común, mientras que seriar implica ordenarlos según un criterio de variación."},
    {q:"En Infantil, antes de trabajar el número, resulta fundamental el desarrollo de:",
     o:["La escritura de cifras de forma mecánica","El pensamiento lógico y las nociones de cantidad a través de la manipulación","El cálculo mental complejo","Las tablas de multiplicar"],
     c:1, e:"El acceso al número debe apoyarse en experiencias manipulativas y lógicas previas (comparar, clasificar, seriar, estimar cantidades), no en la escritura mecánica de cifras."},
    {q:"El uso de material manipulativo como los bloques lógicos de Dienes tiene como finalidad principal:",
     o:["Desarrollar la clasificación y las relaciones lógicas a partir de atributos (forma, color, tamaño, grosor)","Enseñar exclusivamente los colores primarios","Sustituir el juego simbólico","Trabajar únicamente la psicomotricidad gruesa"],
     c:0, e:"Los bloques lógicos de Zoltan Dienes permiten trabajar la clasificación, seriación y relaciones lógicas a partir de sus cuatro atributos: forma, color, tamaño y grosor."}
  ]
},
{
  id: "b13", title: "Influencia de las Principales Corrientes Pedagógicas y Psicológicas en la Educación Infantil",
  questions: [
    {q:"María Montessori es la creadora de un método pedagógico basado, entre otros principios, en:",
     o:["La instrucción directa y memorística","El ambiente preparado, la autonomía y el material autocorrectivo","La ausencia total de materiales estructurados","El aprendizaje exclusivamente grupal sin trabajo individual"],
     c:1, e:"El método Montessori se basa en preparar un ambiente adecuado, respetar los periodos sensibles y favorecer la autonomía mediante materiales autocorrectivos."},
    {q:"Ovide Decroly es conocido pedagógicamente por su propuesta de:",
     o:["Los 'centros de interés' y la globalización de la enseñanza","Las 'casas de los niños' (Case dei Bambini)","La pedagogía del texto libre","Los rincones de actividad exclusivamente"],
     c:0, e:"Decroly organizó el currículo en torno a 'centros de interés' ligados a las necesidades básicas del niño, defendiendo un enfoque globalizador del aprendizaje."},
    {q:"Célestin Freinet es reconocido, entre otras aportaciones, por introducir en la escuela técnicas como:",
     o:["El texto libre, la imprenta escolar y la correspondencia escolar","Los dones o Gaben","Las tarjetas de nomenclatura","La pedagogía Waldorf"],
     c:0, e:"Freinet desarrolló técnicas activas y cooperativas como el texto libre, la imprenta escolar, la correspondencia interescolar y la asamblea de clase."},
    {q:"La 'Escuela Nueva' o 'Escuela Activa', movimiento pedagógico de finales del s. XIX y principios del XX, se caracteriza por:",
     o:["Situar al niño como centro del proceso educativo, frente a la escuela tradicional memorística","Defender la enseñanza puramente transmisiva del adulto","Rechazar cualquier tipo de actividad manipulativa","Priorizar exclusivamente la evaluación por exámenes"],
     c:0, e:"La Escuela Nueva sitúa al niño como protagonista activo del aprendizaje, frente al modelo tradicional centrado en la transmisión pasiva de contenidos."},
    {q:"Loris Malaguzzi es el impulsor de la conocida experiencia educativa de:",
     o:["Reggio Emilia","Summerhill","Waldorf-Steiner","Sistema Montessori"],
     c:0, e:"Malaguzzi fue el impulsor de las escuelas municipales de Reggio Emilia (Italia), que defienden al niño como 'sujeto de derechos' y otorgan gran valor al ambiente y a los 'cien lenguajes' del niño."},
    {q:"Henri Wallon aportó a la psicología del desarrollo infantil, entre otros, el concepto de:",
     o:["Los estadios del desarrollo con un enfoque dialéctico entre lo afectivo, motor y cognitivo","El condicionamiento clásico","La zona de desarrollo próximo","Los periodos sensibles"],
     c:0, e:"Wallon propuso una teoría de estadios que subraya la relación dialéctica entre emoción, movimiento e inteligencia como motores del desarrollo psicológico infantil."}
  ]
},
{
  id: "b14", title: "La Educación Musical en Educación Infantil",
  questions: [
    {q:"El método pedagógico-musical de Carl Orff se caracteriza especialmente por:",
     o:["El uso del cuerpo (percusión corporal), la palabra y los instrumentos de placas Orff","Ser exclusivamente teórico, sin práctica instrumental","Basarse únicamente en la escritura de partituras","Estar dirigido solo a la etapa adulta"],
     c:0, e:"Orff propone partir de elementos básicos como la palabra, el ritmo, el movimiento y la percusión corporal, junto a instrumentos de placas de fácil manejo."},
    {q:"El método Kodály otorga especial importancia a:",
     o:["El canto y la voz como instrumento musical fundamental","El uso exclusivo de instrumentos de viento","La ausencia total de canciones populares","La memorización de partituras complejas desde bebés"],
     c:0, e:"Zoltán Kodály defiende la voz cantada, especialmente a través del folclore y canciones populares, como base fundamental de la educación musical."},
    {q:"El método Dalcroze se centra especialmente en:",
     o:["La euritmia, es decir, la relación entre música y movimiento corporal","La escritura musical exclusivamente","La ausencia de instrumentos","El aprendizaje de idiomas"],
     c:0, e:"Émile Jaques-Dalcroze desarrolló la euritmia, un método que vincula estrechamente el ritmo musical con el movimiento corporal."},
    {q:"Los parámetros básicos del sonido que se trabajan en Educación Infantil son:",
     o:["Altura, intensidad, duración y timbre","Melodía, armonía y contrapunto exclusivamente","Solo el ritmo","Únicamente la letra de las canciones"],
     c:0, e:"Los cuatro parámetros básicos del sonido son altura (agudo-grave), intensidad (fuerte-suave), duración (largo-corto) y timbre (color del sonido)."},
    {q:"La audición musical activa en el aula de Infantil tiene como finalidad principal:",
     o:["Que el alumnado permanezca en silencio sin ninguna actividad","Desarrollar la escucha, la discriminación auditiva y la sensibilidad estética","Memorizar biografías de compositores","Sustituir el lenguaje verbal"],
     c:1, e:"La audición activa busca desarrollar capacidades de escucha, discriminación de sonidos y sensibilización estética, a menudo combinada con movimiento o representación gráfica."},
    {q:"Los instrumentos de pequeña percusión (como panderetas, claves o maracas) en Infantil se utilizan preferentemente para:",
     o:["Ejecutar partituras complejas de forma individual","Explorar el ritmo, la coordinación y el trabajo en grupo de forma vivencial","Sustituir la voz cantada","Solo como decoración del aula"],
     c:1, e:"Estos instrumentos permiten una aproximación vivencial y manipulativa al ritmo, favoreciendo la coordinación motriz y la experiencia musical colectiva."}
  ]
},
{
  id: "b15", title: "La Educación Sexual en la Etapa Infantil",
  questions: [
    {q:"La educación sexual en la etapa infantil debe entenderse fundamentalmente como:",
     o:["Educación afectivo-sexual integral: identidad, cuerpo, afectos y respeto, adaptada a la edad","Un tema tabú que no debe abordarse en el aula","Únicamente información biológica sobre la reproducción","Una responsabilidad exclusiva de la familia sin implicación escolar"],
     c:0, e:"En Infantil se aborda la educación afectivo-sexual de forma integral y adaptada: conocimiento y aceptación del propio cuerpo, identidad, afectos, respeto y prevención del abuso."},
    {q:"En torno a los 2-3 años, los niños y niñas suelen alcanzar:",
     o:["La identidad de género básica, es decir, se reconocen a sí mismos como niño o niña","La comprensión adulta completa de la sexualidad","La total indiferencia respecto al propio cuerpo","El rechazo generalizado hacia el propio cuerpo"],
     c:0, e:"Alrededor de los 2-3 años se consolida la identidad de género básica: el niño o niña se identifica y nombra a sí mismo/a según su género."},
    {q:"La curiosidad exploratoria del propio cuerpo (autoexploración) en la etapa infantil debe entenderse, en general, como:",
     o:["Un comportamiento normativo del desarrollo que debe abordarse con naturalidad y sin dramatismo","Siempre un signo de abuso sexual","Una conducta que debe castigarse severamente","Un tema que nunca debe mencionarse en clase"],
     c:0, e:"La exploración corporal es parte habitual del desarrollo infantil; el papel educativo consiste en acompañarla con naturalidad, respeto e información adecuada a la edad."},
    {q:"Uno de los objetivos de la educación afectivo-sexual en Infantil es la prevención del abuso sexual infantil, principalmente a través de:",
     o:["Enseñar al niño a identificar partes de su cuerpo, decir 'no' y contarlo a un adulto de confianza","Evitar cualquier mención al cuerpo","Enseñar exclusivamente contenidos biológicos avanzados","Delegar totalmente la responsabilidad en la familia"],
     c:0, e:"La prevención se basa en el conocimiento del propio cuerpo, el derecho a decir 'no' ante situaciones que incomodan, y la confianza para comunicarlo a un adulto."},
    {q:"El respeto a la diversidad de modelos familiares (familias monoparentales, homoparentales, reconstituidas...) forma parte de:",
     o:["Un contenido ajeno a la educación afectivo-sexual","La educación en igualdad y respeto propia de la educación afectivo-sexual y en valores","Un tema exclusivo de la etapa de Secundaria","Un contenido prohibido en la escuela infantil"],
     c:1, e:"El reconocimiento y respeto por la diversidad familiar y afectiva forma parte de una educación afectivo-sexual inclusiva desde las primeras edades."},
    {q:"El lenguaje adecuado para nombrar las partes del cuerpo, incluidos los genitales, en la etapa infantil debe ser:",
     o:["Eufemístico y evasivo siempre","Correcto, natural y sin connotaciones negativas, adaptado a la comprensión infantil","Evitado por completo en el aula","Exclusivamente técnico-médico y complejo"],
     c:1, e:"Se recomienda utilizar un lenguaje correcto y natural para nombrar el cuerpo, incluidos los genitales, contribuyendo a una relación sana y sin tabúes con el propio cuerpo."}
  ]
},
{
  id: "b16", title: "La Enseñanza y el Aprendizaje de la Lengua en la Educación Infantil",
  questions: [
    {q:"El enfoque comunicativo en la enseñanza de la lengua en Infantil prioriza:",
     o:["El uso funcional y contextualizado del lenguaje en situaciones reales de comunicación","La enseñanza de reglas gramaticales de forma explícita y descontextualizada","Exclusivamente ejercicios de repetición mecánica","La lectoescritura formal desde los dos años"],
     c:0, e:"El enfoque comunicativo se centra en que el lenguaje se use de forma funcional en contextos significativos, priorizando la comunicación sobre la corrección formal explícita."},
    {q:"Según la LOMLOE, en Educación Infantil el acercamiento a la lectoescritura debe realizarse:",
     o:["De forma sistemática y obligatoria desde los tres años con métodos formales","De forma progresiva y contextualizada, respetando el proceso evolutivo, sin carácter de enseñanza formal y sistemática obligatoria","Prohibiéndose cualquier contacto con la lengua escrita","Solo a través de fichas de caligrafía repetitiva"],
     c:1, e:"El marco curricular actual plantea un acercamiento progresivo y funcional a la lengua escrita, evitando la enseñanza formal, sistemática y descontextualizada de la lectoescritura."},
    {q:"El enfoque constructivista sobre la adquisición de la lengua escrita, con autoras como Emilia Ferreiro y Ana Teberosky, defiende que el niño:",
     o:["Es un sujeto pasivo que recibe la escritura ya elaborada","Construye activamente hipótesis sobre el sistema de escritura antes de dominarlo convencionalmente","No puede tener ninguna idea sobre la escritura antes de los 6 años","Aprende a escribir exclusivamente por repetición mecánica"],
     c:1, e:"Ferreiro y Teberosky demostraron que los niños elaboran hipótesis propias (presilábica, silábica, silábico-alfabética, alfabética) en su acercamiento constructivo a la lengua escrita."},
    {q:"La asamblea o el 'corro' de buenos días es un recurso metodológico especialmente valioso para trabajar:",
     o:["La expresión oral, la escucha y las habilidades comunicativas en grupo","Exclusivamente la psicomotricidad fina","La lectoescritura formal","Las matemáticas avanzadas"],
     c:0, e:"La asamblea diaria es un momento privilegiado para fomentar la expresión oral, la escucha activa, el respeto de turnos y las habilidades comunicativas grupales."},
    {q:"El cuento y la narración oral en el aula de Infantil favorecen especialmente:",
     o:["El desarrollo del vocabulario, la comprensión narrativa y la imaginación","Únicamente la memoria mecánica de textos","La psicomotricidad gruesa exclusivamente","El cálculo matemático"],
     c:0, e:"La narración de cuentos amplía el vocabulario, desarrolla la comprensión de estructuras narrativas y estimula la imaginación y la capacidad simbólica."},
    {q:"El bilingüismo o plurilingüismo temprano en la etapa infantil, según la evidencia actual, tiende a:",
     o:["Perjudicar siempre el desarrollo cognitivo del niño","Ser compatible con un desarrollo lingüístico adecuado, favoreciendo incluso ciertas habilidades cognitivas","Provocar necesariamente retraso del lenguaje","Ser desaconsejado en cualquier caso antes de los 6 años"],
     c:1, e:"La investigación actual señala que la exposición a varias lenguas desde la infancia es compatible con un desarrollo lingüístico saludable y puede favorecer habilidades como la flexibilidad cognitiva."}
  ]
},
{
  id: "b17", title: "La Expresión Corporal",
  questions: [
    {q:"La expresión corporal en Infantil se define como un lenguaje que utiliza el cuerpo y el movimiento con una finalidad:",
     o:["Exclusivamente deportiva y competitiva","Comunicativa, expresiva y creativa","Únicamente terapéutica clínica","Solo evaluable mediante pruebas físicas estandarizadas"],
     c:1, e:"La expresión corporal utiliza el cuerpo como instrumento de comunicación, expresión de emociones y creación, más allá de la mera ejecución motriz o deportiva."},
    {q:"El juego simbólico y la dramatización espontánea (jugar a ser 'mamá', 'médico'...) forman parte de:",
     o:["La expresión corporal y contribuyen al desarrollo de la representación simbólica","Un contenido exclusivo del área matemática","Una actividad sin ninguna relación con la expresión corporal","Solo el ámbito de la música"],
     c:0, e:"El juego simbólico y la dramatización son manifestaciones de la expresión corporal que además favorecen el desarrollo de la función simbólica descrita por Piaget."},
    {q:"En las sesiones de expresión corporal en Infantil, el papel del maestro o maestra debe ser preferentemente:",
     o:["Dirigir de forma rígida cada movimiento sin margen de creatividad","Facilitar, proponer estímulos y respetar la creatividad e iniciativa infantil","Evaluar exclusivamente la técnica con criterios de danza profesional","No intervenir nunca en ningún sentido"],
     c:1, e:"El docente actúa como facilitador, proponiendo estímulos (música, objetos, consignas abiertas) y respetando la libre expresión y creatividad de cada niño o niña."},
    {q:"El trabajo del esquema corporal y la imagen corporal a través de la expresión corporal contribuye especialmente al desarrollo:",
     o:["Exclusivamente cognitivo-matemático","Psicomotor y de la identidad personal","Únicamente auditivo","Solo del lenguaje escrito"],
     c:1, e:"La expresión corporal favorece el conocimiento y control del propio cuerpo (esquema corporal) y la construcción de la propia identidad e imagen corporal."},
    {q:"La utilización de música, objetos o consignas verbales como estímulo para la expresión corporal tiene como finalidad:",
     o:["Sustituir totalmente la creatividad del niño","Servir de punto de partida que estimule la respuesta motriz y expresiva personal","Imponer un único movimiento correcto","Evaluar exclusivamente la memoria auditiva"],
     c:1, e:"Los estímulos externos (música, objetos, consignas) actúan como disparadores de la creatividad, dejando siempre espacio a la respuesta personal de cada niño."},
    {q:"El mimo y la imitación gestual en Infantil favorecen especialmente:",
     o:["La capacidad de observación, la representación simbólica y el control corporal","Exclusivamente la lectoescritura","El cálculo matemático avanzado","La memorización de vocabulario técnico"],
     c:0, e:"El mimo y la imitación desarrollan la observación, la representación simbólica del cuerpo y un mayor control y conciencia corporal."}
  ]
},
{
  id: "b18", title: "La Familia Como Primer Agente de Socialización",
  questions: [
    {q:"La familia se considera el primer agente de socialización porque:",
     o:["Es la primera institución con la que el niño establece vínculos afectivos y aprende pautas sociales básicas","Es la única institución que interviene en la socialización del niño","Solo tiene función económica","No influye en el desarrollo afectivo"],
     c:0, e:"La familia proporciona los primeros vínculos afectivos y modelos de conducta, siendo el contexto primario donde se inicia el proceso de socialización."},
    {q:"La relación entre la escuela infantil y la familia debe basarse fundamentalmente en el principio de:",
     o:["Delegación total de responsabilidades de una parte a la otra","Colaboración, complementariedad y comunicación bidireccional","Ausencia de contacto para no interferir","Competencia entre ambas instituciones"],
     c:1, e:"La colaboración escuela-familia, basada en la comunicación fluida y bidireccional, resulta fundamental para el bienestar y desarrollo integral del niño."},
    {q:"El 'periodo de adaptación' al inicio de la escolarización tiene como principal finalidad:",
     o:["Separar de forma brusca al niño de la familia","Facilitar de forma gradual la transición del entorno familiar al escolar, minimizando la angustia de separación","Evaluar el nivel académico del niño","Sustituir definitivamente el vínculo familiar"],
     c:1, e:"El periodo de adaptación busca una transición progresiva y respetuosa entre el ámbito familiar y escolar, atendiendo a la angustia de separación propia de estas edades."},
    {q:"Según la clasificación clásica de estilos educativos parentales (Baumrind), el estilo caracterizado por afecto y normas claras y razonadas se denomina:",
     o:["Estilo autoritario","Estilo democrático o autorizativo","Estilo permisivo","Estilo negligente"],
     c:1, e:"Baumrind describe el estilo democrático (o autorizativo) como aquel que combina afecto, comunicación y normas claras y razonadas, asociado a mejores resultados en el desarrollo infantil."},
    {q:"Las escuelas de familias o escuelas de madres y padres organizadas desde los centros de Infantil tienen como objetivo principal:",
     o:["Sustituir la función educativa de la familia","Ofrecer formación, apoyo y espacios de reflexión a las familias sobre la crianza y educación","Evaluar negativamente a las familias","Excluir a las familias de la vida del centro"],
     c:1, e:"Estas iniciativas buscan acompañar, formar y crear espacios de encuentro y reflexión conjunta entre familias sobre temas relacionados con la crianza y la educación."},
    {q:"La actual diversidad de estructuras familiares (nucleares, monoparentales, reconstituidas, homoparentales, etc.) debe abordarse desde la escuela con:",
     o:["Rechazo hacia los modelos no tradicionales","Normalidad, respeto y sin establecer jerarquías entre modelos familiares","Silencio absoluto sobre el tema","Trato diferenciado y desigual según el tipo de familia"],
     c:1, e:"La escuela debe reconocer y respetar la diversidad de modelos familiares existentes en la sociedad actual, evitando cualquier forma de discriminación."}
  ]
},
{
  id: "b19", title: "La Función del Maestro o Maestra en Educación Infantil",
  questions: [
    {q:"El rol del maestro o maestra de Educación Infantil se define principalmente como:",
     o:["Transmisor exclusivo de contenidos académicos","Mediador, guía y acompañante del proceso de desarrollo y aprendizaje","Figura exclusivamente de cuidado asistencial, sin función pedagógica","Evaluador cuya única tarea es calificar"],
     c:1, e:"El docente de Infantil actúa como mediador y guía, creando ambientes ricos en estímulos y acompañando el desarrollo integral del alumnado, más allá de la mera transmisión de contenidos."},
    {q:"La observación sistemática del alumnado por parte del maestro o maestra en Infantil cumple, sobre todo, la función de:",
     o:["Ser el principal instrumento de evaluación continua y ajuste de la intervención educativa","No tener ninguna utilidad práctica","Sustituir a la programación didáctica","Ser exclusiva del segundo ciclo de Infantil"],
     c:0, e:"En esta etapa, la observación directa y sistemática es la técnica de evaluación por excelencia, permitiendo ajustar la intervención educativa a las necesidades reales del alumnado."},
    {q:"El principio de 'individualización' de la enseñanza en Infantil implica que el maestro o maestra debe:",
     o:["Aplicar exactamente el mismo ritmo y actividades a todo el grupo sin excepción","Ajustar la intervención educativa a las características, ritmos e intereses de cada niño o niña","Renunciar a cualquier planificación previa","Atender exclusivamente al alumnado con necesidades específicas de apoyo educativo"],
     c:1, e:"La individualización supone respetar y atender la diversidad de ritmos, intereses y necesidades de cada niño dentro del grupo, sin renunciar a la planificación."},
    {q:"El trabajo en equipo docente (coordinación entre tutores, especialistas y equipo de orientación) en Infantil es importante fundamentalmente para:",
     o:["Garantizar la coherencia y continuidad de la intervención educativa","Aumentar innecesariamente la burocracia del centro","Sustituir la relación con las familias","No tiene relevancia en esta etapa"],
     c:0, e:"La coordinación docente asegura coherencia, continuidad y una respuesta educativa ajustada y compartida ante las necesidades del alumnado."},
    {q:"El maestro o maestra de Infantil, al organizar el ambiente y las actividades, actúa desde el enfoque constructivista fundamentalmente como:",
     o:["Un mero transmisor de información memorística","Un mediador que facilita la construcción activa del propio aprendizaje por parte del niño","Un evaluador ajeno al proceso de enseñanza","Una figura exclusivamente de vigilancia"],
     c:1, e:"Desde el constructivismo, el docente crea condiciones y media para que sea el propio niño quien construya activamente su aprendizaje, en interacción con el entorno y los demás."},
    {q:"La formación permanente y la reflexión sobre la propia práctica docente (práctica reflexiva) se consideran:",
     o:["Innecesarias una vez obtenida la titulación inicial","Un elemento clave de la profesionalidad docente para la mejora continua","Responsabilidad exclusiva de la administración educativa","Contrarias a la autonomía del centro"],
     c:1, e:"La formación continua y la reflexión sobre la propia práctica constituyen elementos esenciales del desarrollo profesional docente y de la mejora educativa."}
  ]
},
{
  id: "b20", title: "La Influencia de la Imagen en el Niño",
  questions: [
    {q:"La 'alfabetización audiovisual' en Educación Infantil hace referencia a:",
     o:["Enseñar exclusivamente a leer texto escrito","Desarrollar capacidades de comprensión y análisis crítico de las imágenes y medios audiovisuales","Prohibir cualquier contacto con imágenes en el aula","Un contenido exclusivo de etapas educativas superiores"],
     c:1, e:"La alfabetización audiovisual busca que, desde edades tempranas, el niño desarrolle una mirada comprensiva y crítica ante las imágenes y los medios de comunicación."},
    {q:"Según recomendaciones de organismos como la Academia Americana de Pediatría, el uso de pantallas en menores de 2 años debe ser:",
     o:["Ilimitado y fomentado desde el nacimiento","Evitado en general, salvo videollamadas puntuales, priorizando la interacción directa","Obligatorio como parte del currículo","Exclusivamente educativo sin ninguna restricción horaria"],
     c:1, e:"Las principales recomendaciones pediátricas desaconsejan el uso de pantallas en menores de 2 años (salvo videollamadas), priorizando la interacción social directa y el juego."},
    {q:"La imagen (fotografías, pictogramas, ilustraciones de cuentos) se utiliza en el aula de Infantil como recurso principalmente para:",
     o:["Sustituir totalmente el lenguaje oral","Apoyar la comprensión, la comunicación y el acceso a la información de forma motivadora","Evaluar exclusivamente el nivel matemático","Sustituir el juego"],
     c:1, e:"La imagen es un potente recurso didáctico que apoya la comprensión, motiva el aprendizaje y facilita el acceso a la información y a la narrativa (por ejemplo, en los cuentos)."},
    {q:"El análisis crítico de estereotipos (de género, culturales, etc.) transmitidos por dibujos animados o publicidad infantil forma parte de:",
     o:["Un tema irrelevante en Infantil","La educación en valores y el desarrollo del pensamiento crítico, incluso en edades tempranas","Un contenido exclusivo de Bachillerato","Una tarea que corresponde solo a las familias"],
     c:1, e:"Analizar críticamente los estereotipos transmitidos por los medios forma parte de la educación en valores e igualdad que debe iniciarse desde la etapa infantil, de forma adaptada."},
    {q:"El pictograma, como recurso de comunicación visual, resulta especialmente útil en Infantil para:",
     o:["Sustituir por completo el lenguaje oral y escrito","Apoyar la comunicación, la anticipación de rutinas y la inclusión de alumnado con necesidades específicas","Ser usado únicamente en matemáticas","No tiene ninguna utilidad pedagógica"],
     c:1, e:"Los pictogramas apoyan la comunicación (especialmente en alumnado con dificultades comunicativas), ayudan a anticipar rutinas y estructurar el tiempo de forma visual."},
    {q:"La sobreexposición temprana a pantallas se ha relacionado en diversos estudios con posibles efectos negativos sobre:",
     o:["El desarrollo del lenguaje, la atención y la calidad del sueño","Ningún aspecto del desarrollo","Exclusivamente el desarrollo motor grueso","Solo el rendimiento en matemáticas en la etapa adulta"],
     c:0, e:"Diversos estudios asocian el uso excesivo y no acompañado de pantallas en edades tempranas con posibles dificultades en el desarrollo del lenguaje, la atención y el sueño."}
  ]
},
{
  id: "b21", title: "La Literatura Infantil",
  questions: [
    {q:"La literatura infantil, desde el punto de vista educativo, cumple una doble función:",
     o:["Exclusivamente instructiva y moralizante","Estética/lúdica y formativa (desarrollo lingüístico, cognitivo y emocional)","Únicamente decorativa en el aula","Solo evaluativa del nivel lector"],
     c:1, e:"La literatura infantil combina una función estética y de disfrute con una función formativa, contribuyendo al desarrollo lingüístico, cognitivo, emocional y social del niño."},
    {q:"La estructura narrativa típica de los cuentos populares o tradicionales (planteamiento, nudo y desenlace) ayuda al niño a:",
     o:["Confundirse respecto a la secuencia temporal","Desarrollar el sentido de la estructura narrativa y la comprensión de secuencias temporales y causales","No tiene ninguna función cognitiva","Sustituir el lenguaje oral"],
     c:1, e:"La estructura clásica de introducción, nudo y desenlace favorece que el niño interiorice patrones narrativos y desarrolle la comprensión de secuencias temporales y causales."},
    {q:"Los cuentos con estructura acumulativa o repetitiva (como 'La gallinita roja' o cuentos de fórmula) resultan especialmente adecuados en Infantil porque:",
     o:["Dificultan la comprensión del relato","Favorecen la anticipación, la memoria y la participación activa del niño en la narración","No tienen ninguna utilidad didáctica","Solo sirven para niños mayores de diez años"],
     c:1, e:"La repetición y acumulación de elementos facilita que el niño anticipe lo que va a suceder, participe activamente en la narración y ejercite la memoria."},
    {q:"A la hora de seleccionar cuentos para el aula de Infantil, un criterio fundamental es:",
     o:["Elegir siempre los textos más extensos posibles","La adecuación del vocabulario, la temática y la estructura a la edad e intereses del grupo","Priorizar exclusivamente cuentos sin ilustraciones","Evitar cualquier tipo de conflicto o tensión narrativa"],
     c:1, e:"La selección de literatura infantil debe atender a la adecuación evolutiva: vocabulario, extensión, temática, complejidad narrativa e ilustraciones apropiadas a la edad."},
    {q:"La hora del cuento o momento de narración diaria en el aula favorece, entre otros aspectos:",
     o:["Exclusivamente la memorización literal de textos","El vínculo afectivo, el gusto por la lectura y el desarrollo del lenguaje oral","El desarrollo motor grueso exclusivamente","La resolución de problemas matemáticos"],
     c:1, e:"El momento del cuento fortalece el vínculo afectivo adulto-niño, despierta el gusto por la lectura y enriquece el vocabulario y las estructuras del lenguaje oral."},
    {q:"Los álbumes ilustrados, en los que texto e imagen se complementan para construir el significado, se consideran en la actualidad:",
     o:["Un formato marginal sin valor literario","Un formato de gran valor literario y didáctico propio de la literatura infantil contemporánea","Exclusivos para adultos","Incompatibles con la etapa infantil"],
     c:1, e:"El álbum ilustrado, donde texto e imagen dialogan para construir el sentido, es hoy un formato de referencia y gran riqueza dentro de la literatura infantil."}
  ]
},
{
  id: "b22", title: "La Organización de los Espacios y del Tiempo",
  questions: [
    {q:"La organización del espacio en rincones o ambientes de aprendizaje responde al principio metodológico de:",
     o:["Fomentar la actividad autónoma, la elección y el aprendizaje significativo del alumnado","Facilitar exclusivamente el control disciplinario","Homogeneizar la actividad de todo el grupo","Reducir la interacción entre iguales"],
     c:0, e:"La organización por rincones favorece la autonomía, la libre elección y experiencias de aprendizaje activas y significativas, adaptadas a los intereses del alumnado."},
    {q:"El concepto de 'rutina' en Educación Infantil se refiere a:",
     o:["Actividades repetitivas sin ningún valor educativo","Secuencias de actividades estables que ofrecen seguridad, referencias temporales y autonomía","Un método exclusivo de evaluación","Una técnica de expresión plástica"],
     c:1, e:"Las rutinas (entrada, asamblea, aseo, comida...) aportan estabilidad, previsibilidad y seguridad afectiva, además de ayudar a estructurar el tiempo y fomentar la autonomía."},
    {q:"Según Loris Malaguzzi, referente de Reggio Emilia, el espacio del aula se concibe como:",
     o:["Un elemento neutro sin relevancia pedagógica","El 'tercer maestro', con un papel activo en el proceso educativo","Un lugar exclusivamente de almacenamiento de materiales","Un espacio que debe permanecer inmutable durante todo el curso"],
     c:1, e:"Malaguzzi acuñó la expresión del ambiente como 'tercer educador' (junto a la familia y el docente), destacando su papel activo en el proceso de enseñanza-aprendizaje."},
    {q:"La organización flexible del tiempo escolar en Infantil debe compatibilizar:",
     o:["La estabilidad de las rutinas con cierta flexibilidad ante imprevistos e intereses emergentes","Una rigidez absoluta sin ningún margen de adaptación","La ausencia total de estructura temporal","Horarios idénticos a los de Educación Primaria"],
     c:0, e:"Se busca un equilibrio entre la seguridad que aportan las rutinas estables y la flexibilidad necesaria para adaptarse a imprevistos, ritmos individuales e intereses puntuales."},
    {q:"Los criterios básicos que debe cumplir el espacio del aula de Infantil incluyen:",
     o:["Seguridad, accesibilidad, flexibilidad y estimulación sensorial adecuada","Uniformidad absoluta y ausencia de estímulos","Espacios cerrados sin posibilidad de reorganización","Prioridad exclusiva del mobiliario sobre la seguridad"],
     c:0, e:"El espacio debe ser seguro, accesible, flexible (adaptable a distintas actividades) y ofrecer una estimulación sensorial equilibrada, ni excesiva ni pobre."},
    {q:"El momento de la 'asamblea' al inicio de la jornada cumple, entre otras, la función de:",
     o:["Estructurar temporalmente el día, favorecer la comunicación grupal y crear sentido de pertenencia","No tener relación con la organización del tiempo","Sustituir el periodo de adaptación","Evaluar exclusivamente contenidos matemáticos"],
     c:0, e:"La asamblea inicial ayuda a situar temporalmente la jornada (día, fecha, clima...), fomenta la comunicación grupal y refuerza el sentido de pertenencia al grupo."}
  ]
},
{
  id: "b23", title: "La Programación en el Primer Ciclo de Educación Infantil",
  questions: [
    {q:"La programación en el primer ciclo (0-3 años) debe caracterizarse especialmente por:",
     o:["Una gran flexibilidad y atención individualizada a las necesidades básicas y ritmos de cada niño o niña","Una rigidez similar a la de Educación Primaria","La ausencia total de planificación previa","Priorizar exclusivamente contenidos académicos formales"],
     c:0, e:"En el primer ciclo la programación debe ser especialmente flexible, priorizando la atención a las necesidades básicas (afectivas, fisiológicas) y el respeto al ritmo individual."},
    {q:"En el primer ciclo, los elementos curriculares (objetivos, contenidos, metodología) los concreta principalmente:",
     o:["Cada centro, a través de su propuesta pedagógica, dado el carácter no regulado en currículo estatal detallado como en el segundo ciclo","Exclusivamente el Ministerio de Educación con un currículo cerrado idéntico al de Primaria","Las familias de forma individual para cada niño","No existe ningún tipo de planificación en este ciclo"],
     c:0, e:"El primer ciclo se rige por una 'propuesta pedagógica' elaborada por cada centro, dentro del marco autonómico, con gran flexibilidad respecto a un currículo cerrado."},
    {q:"El documento que recoge las líneas pedagógicas generales del primer ciclo en cada centro (0-3 años) se denomina habitualmente:",
     o:["Programación General Anual exclusivamente","Propuesta pedagógica","Reglamento de Régimen Interno únicamente","Proyecto Lingüístico de Centro"],
     c:1, e:"La propuesta pedagógica es el documento que concreta, en cada centro de primer ciclo, los objetivos, contenidos, metodología y criterios de evaluación adaptados a esta etapa."},
    {q:"La atención a las rutinas de cuidado (alimentación, higiene, sueño) en la programación del primer ciclo se considera:",
     o:["Un aspecto puramente asistencial sin valor pedagógico","Un contenido educativo de primer orden, con gran potencial para el aprendizaje y el vínculo afectivo","Algo que debe evitarse en el aula","Responsabilidad exclusiva de las familias"],
     c:1, e:"En el primer ciclo, los momentos de cuidado (comida, higiene, sueño) son situaciones educativas de primer orden, ricas en interacción, vínculo afectivo y aprendizaje."},
    {q:"La ratio (número de niños por adulto) es un aspecto especialmente relevante en la programación del primer ciclo porque:",
     o:["No influye en absoluto en la calidad educativa","Condiciona directamente la calidad de la atención individualizada y del vínculo afectivo","Solo afecta a aspectos administrativos sin relación pedagógica","Es idéntica en todos los tramos de edad del primer ciclo"],
     c:1, e:"Una ratio adecuada resulta clave en el primer ciclo para poder ofrecer una atención individualizada, sensible y de calidad, especialmente en los tramos de menor edad."},
    {q:"La evaluación en el primer ciclo de Educación Infantil se basa fundamentalmente en:",
     o:["Pruebas escritas estandarizadas","La observación directa y sistemática del desarrollo global del niño o niña","Exámenes orales formales","Calificaciones numéricas"],
     c:1, e:"En el primer ciclo, dada la corta edad del alumnado, la evaluación se realiza mediante observación directa, continua y global del desarrollo, sin pruebas formales."}
  ]
},
{
  id: "b24", title: "La Programación en el Segundo Ciclo de Educación Infantil",
  questions: [
    {q:"El segundo ciclo de Educación Infantil (3-6 años) tiene, a diferencia del primero, carácter:",
     o:["No gratuito en ningún caso y opcional sin regulación curricular","Gratuito y con un currículo regulado (objetivos, áreas, contenidos y criterios de evaluación) por la administración educativa","Obligatorio en todo el territorio español","Idéntico en objetivos y metodología a Educación Primaria"],
     c:1, e:"El segundo ciclo es gratuito (aunque no obligatorio) y cuenta con un currículo oficial regulado por la administración educativa, a diferencia del primer ciclo, más flexible."},
    {q:"En el segundo ciclo, el documento que concreta la programación para un grupo o nivel concreto, partiendo del Proyecto Educativo de Centro, se denomina habitualmente:",
     o:["Programación didáctica o de aula","Reglamento de Régimen Interno","Plan de convivencia","Proyecto de gestión económica"],
     c:0, e:"La programación didáctica (o programación de aula) concreta, para un grupo y curso determinados, los objetivos, contenidos, metodología, actividades y evaluación del segundo ciclo."},
    {q:"Los elementos que debe incluir toda programación didáctica en el segundo ciclo son, entre otros:",
     o:["Objetivos, contenidos, metodología, actividades, recursos y criterios de evaluación","Únicamente una lista de actividades sin objetivos ni evaluación","Solo el horario semanal","Exclusivamente el listado de materiales fungibles"],
     c:0, e:"Una programación didáctica completa debe recoger objetivos, contenidos, metodología, actividades, recursos, atención a la diversidad y criterios/procedimientos de evaluación."},
    {q:"La atención a la diversidad dentro de la programación del segundo ciclo debe contemplar:",
     o:["Medidas y adaptaciones para responder a los diferentes ritmos, capacidades e intereses del alumnado","Un único itinerario idéntico para todo el alumnado sin excepciones","La exclusión del alumnado con necesidades específicas de apoyo educativo","Ignorar las diferencias individuales"],
     c:0, e:"Toda programación debe prever medidas de atención a la diversidad (adaptaciones, refuerzos, ampliaciones) para responder a la heterogeneidad propia de cualquier grupo."},
    {q:"Los criterios de evaluación en el segundo ciclo de Infantil se formulan en relación con:",
     o:["El grado de consecución de las capacidades y objetivos propios de la etapa y de cada área","Calificaciones numéricas del 1 al 10","Exámenes estandarizados externos","Comparaciones directas entre el alumnado del grupo"],
     c:0, e:"Los criterios de evaluación se refieren al grado de desarrollo de las capacidades y objetivos establecidos, evaluando de forma global, continua y formativa, sin calificaciones numéricas."},
    {q:"La programación por 'proyectos de trabajo', metodología habitual en el segundo ciclo, se caracteriza por:",
     o:["Partir de los intereses del alumnado y organizar los aprendizajes de forma globalizada en torno a un tema","Seguir siempre un libro de texto de forma lineal","Excluir la participación del alumnado en su propio proceso de aprendizaje","Centrarse exclusivamente en fichas de repaso"],
     c:0, e:"Los proyectos de trabajo parten de los intereses e inquietudes del alumnado, organizando los aprendizajes de forma globalizada e investigativa en torno a un tema significativo."}
  ]
},
{
  id: "b25", title: "Principios de Intervención Educativa de Educación Infantil",
  questions: [
    {q:"El principio de 'aprendizaje significativo' (Ausubel), aplicado a Infantil, implica que los nuevos aprendizajes deben:",
     o:["Ser memorizados de forma mecánica sin relación con lo previo","Conectar con los conocimientos y experiencias previas del niño para integrarse de forma comprensiva","Presentarse siempre de forma abstracta y descontextualizada","Evaluarse exclusivamente mediante pruebas escritas"],
     c:1, e:"El aprendizaje significativo requiere que los nuevos contenidos se relacionen con las ideas y experiencias previas del niño, dotando de sentido al aprendizaje."},
    {q:"El principio de 'globalización' en Educación Infantil hace referencia a que:",
     o:["El niño percibe e interpreta la realidad de forma global, no fragmentada en disciplinas o áreas aisladas","Los contenidos deben trabajarse siempre de forma separada por asignaturas","Solo se aplica al área de lenguaje","Es un principio exclusivo del segundo ciclo"],
     c:0, e:"La globalización responde a que el pensamiento infantil percibe la realidad de manera global y no fragmentada, por lo que los aprendizajes deben abordarse de forma integrada."},
    {q:"El principio de 'actividad', como principio metodológico básico en Infantil, defiende que el aprendizaje se produce fundamentalmente a través de:",
     o:["La escucha pasiva de explicaciones del adulto","La acción directa, la manipulación y la experimentación del propio niño","La memorización de contenidos abstractos","Exámenes escritos periódicos"],
     c:1, e:"El principio de actividad sostiene que el niño aprende haciendo, a través de la manipulación, la experimentación directa y la acción sobre el entorno."},
    {q:"El principio de 'individualización' de la enseñanza implica:",
     o:["Aplicar el mismo ritmo y actividades a todos los niños por igual sin excepción","Respetar y atender los distintos ritmos, intereses y niveles de desarrollo de cada niño o niña","Trabajar siempre de forma aislada, sin interacción grupal","Evaluar únicamente mediante pruebas estandarizadas"],
     c:1, e:"La individualización supone ajustar la intervención educativa a las características, ritmo evolutivo e intereses propios de cada niño, dentro de la vida de grupo."},
    {q:"El principio del 'juego' como principio de intervención educativa en Infantil se justifica porque:",
     o:["El juego es una actividad exclusivamente recreativa sin valor educativo","El juego constituye la actividad natural y el motor principal del aprendizaje y desarrollo infantil","Debe limitarse al tiempo de recreo exclusivamente","Es incompatible con la consecución de objetivos curriculares"],
     c:1, e:"El juego se considera el principal instrumento de aprendizaje y desarrollo en la infancia, integrando lo cognitivo, motor, afectivo y social, por lo que debe impregnar la práctica educativa."},
    {q:"El principio de 'clima de seguridad y afectividad' en el aula de Infantil se relaciona directamente con:",
     o:["La teoría del apego y la necesidad de una base emocional segura para que se produzca el aprendizaje","La ausencia de vínculo entre docente y alumnado","La aplicación de normas rígidas sin componente afectivo","Un aspecto secundario sin relación con el aprendizaje"],
     c:0, e:"Un clima afectivo cálido y seguro, coherente con la teoría del apego, constituye la base emocional necesaria para que el niño explore, se relacione y aprenda con confianza."}
  ]
}
];
